### ISSUE TITLE
Not preventing "Open in new tab"

### ISSUE THREAD

**Issue by aries223** [swinggraphics/hotlink-file-prevention#1]
Hello, the plugin is not preventing images from being right-clicked and opened in a new tab then saved from there. 

WP 6.1.1
Theme: Porto Version 6.7.4
Server: Linux 5.4.0-137-generic x86_64
PHP: 7.4.3-4ubuntu2.17 
Web Server: Apache

**Comment by swinggraphics** [comment]
Yes, it's not designed to block that. When you open an image in a new tab, the referrer is set to the page where you right clicked. This plugin only looks at the referrer.
